### ISSUE TITLE
Custom fields no longer appear in WP Alchemy 

### ISSUE THREAD

**Issue by mnizinski79** [farinspace/ama#1]
Logging to to WP and editing a page it looks like the custom fields that were usually appearing with the help of WP Alchemy are no longer showing up. there's no way to edit the content in them. I assume this is a conflict with the latest WordPress release of 4.3.1.

Usually there's an editable textbox below the "Enter Some Text" line. 

![image](https://cloud.githubusercontent.com/assets/7937959/11291884/08a97e2c-8f14-11e5-967b-d7340fb94539.png)

**Comment by farinspace** [comment]
Have a look at https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme this may help with your situation.

At some point in the future I will have to re-review multiple wp_editors.

**Comment by mnizinski79** [comment]
Thank you so much - I did manage to figure it out actually and I think you’re code is still solid. Was something with Tiny MCE not being registered after the a few other scripts that I think may have been dropped in the newer WP version. 

Thank you for replying!

Mike Nizinski
Creative Consulting • Art Direction • Digital Design

678.665.5030
www.mikenizinski.com

On November 20, 2015 at 12:05:24 PM, Dimas Begunoff (notifications@github.com) wrote:

Have a look at https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme this may help with your situation.

At some point in the future I will have to re-review multiple wp_editors.

**Comment by farinspace** [comment]
Great, glade you got it resolved .. do have a read about the Holy Grail Theme, @helgatheviking is pretty awesome and has many insights into WPAlchemy

**Comment by helgatheviking** [comment]
thanks for the shoutout Dimas!
