### ISSUE TITLE
Getting multiple wp_editors in same page

### ISSUE THREAD

**Issue by masterbip** [farinspace/ama#2]
Hi there. Finally got you directly. I am from Chile and I simply love your wpalchemy work. It simplified me the job a LOT.

But I vave been in troble like always. I simply can not got multiple wp_editor instances in the same page. I have tried all the suggestions out ther. Literally. But none is working for me. I must say that all the time i have to use multiple instances is in pages with qtranslate-x running. So maybe this issue is related to this plugin. Can you please take a look on this please? Many many thanks. I waited too much to pay you for the plugin but i did that a month ago or so. Many thanks again for your work.

**Comment by farinspace** [comment]
@masterbip have a look at #1 first and see if any of that might help.

**Comment by masterbip** [comment]
I actually used holy grial ... didn't work, sadly.

I am going to use it in a new test fres wp installation (with qtranslate-x installed) to see what happens.

I'll let you know. Thanks!
